name: build
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2

      - name: Show MinGW version
        run: |
          $env:Path = "C:\\msys64\\mingw64\\bin;$env:Path"
          g++ --version

      - name: Building executable using mingw-w64-x86_64-toolchain from MSYS2
        run: |
          $env:Path = "C:\\msys64\\mingw64\\bin;$env:Path"
          ./build
